name: build_branches

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 15 4 * *' # JST="0 0 5 * *"

jobs:
  make_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        run: |
          echo "TZ=Asia/Tokyo" >> ${GITHUB_ENV}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: test
        run: echo "${{ steps.app-token.outputs.token }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set updated date
        run: echo "UPDATED=$(date --iso-8601=seconds)" >> ${GITHUB_ENV}

      - name: Update README
        run: envsubst '${UPDATED}' < README.md.dist > README.md

      - name: Setup git
        run: |
          git config --global user.name "longkey1"
          git config --global user.email "longkey1@users.noreply.github.com"
          git fetch --all

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README by auto commit"

      - name: Build branches
        run: make build
